name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-nginx:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment directory on the remote server
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "mkdir -p /root/deployment"
      
      - name: Generate .env file
        run: |
          echo "MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}" > .env

      - name: Upload files to remote server
        run: |
          scp -o StrictHostKeyChecking=no ./docker-compose-deploy.yml root@${{ secrets.DROPLET_IP }}:/root/deployment/
          scp -o StrictHostKeyChecking=no ./src/nginx/nginx.conf root@${{ secrets.DROPLET_IP }}:/root/deployment/
          scp -o StrictHostKeyChecking=no .env root@${{ secrets.DROPLET_IP }}:/root/deployment/

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
            cd /root/deployment
            docker-compose --env-file .env -f docker-compose-deploy.yml pull
            docker-compose --env-file .env -f docker-compose-deploy.yml down
            docker-compose --env-file .env -f docker-compose-deploy.yml up -d
          EOF
          